import { App, normalizePath } from "obsidian";
import { GraphStore } from "./graph-store";
import { ClusterInfo } from "../types";

/**
 * Write `_index/VAULT_INDEX.md` and `_index/GRAPH.md` from a built GraphStore.
 *
 * This is the bridge between Phase 2 (graph in memory) and Phase 0/Zettel
 * Connect's index-reader (which expects these markdown files). After running
 * `Cortex: 그래프 빌드 → VAULT_INDEX 다시쓰기`, the recommend panel finally
 * has the data it needs.
 *
 * Format compatibility (mirrors existing index-reader.ts):
 *
 *   VAULT_INDEX.md:
 *     ## 클러스터: <label> (<count>개)
 *     | ID | Claim | Tags | Links |
 *     |----|-------|------|-------|
 *     | id | claim | tag, tag | link, link |
 *
 *   GRAPH.md:
 *     <id> → <link>, <link>
 */

const VAULT_INDEX_PATH = "_index/VAULT_INDEX.md";
const GRAPH_PATH = "_index/GRAPH.md";

export interface WriteResult {
  vaultIndexPath: string;
  graphPath: string;
  clusterCount: number;
  noteCount: number;
  edgeCount: number;
}

export async function writeIndexFiles(
  app: App,
  store: GraphStore,
  clusters: ClusterInfo[],
): Promise<WriteResult> {
  const dir = "_index";
  if (!(await app.vault.adapter.exists(dir))) {
    await app.vault.adapter.mkdir(dir);
  }

  // ── VAULT_INDEX.md ────────────────────────────────────
  const lines: string[] = [];
  lines.push("# VAULT_INDEX\n");
  lines.push("> Auto-generated by Cortex Phase 2. Do not edit by hand — re-run 'Cortex: VAULT_INDEX 다시쓰기'.\n\n");

  // Group nodes by cluster label, skip phantoms.
  const byCluster = new Map<string, Array<{ id: string; claim: string; tags: string[]; outIds: string[] }>>();
  store.forEachNode((id, attrs) => {
    if (attrs.isPhantom) return;
    const label = attrs.cluster || "미분류";
    if (!byCluster.has(label)) byCluster.set(label, []);
    byCluster.get(label)!.push({
      id,
      claim: escapeCell(attrs.claim),
      tags: attrs.tags,
      outIds: outNeighbors(store, id),
    });
  });

  // Sort clusters by size descending; within cluster, sort by id ascending.
  const orderedClusters = [...byCluster.entries()].sort(
    (a, b) => b[1].length - a[1].length,
  );

  for (const [label, members] of orderedClusters) {
    members.sort((a, b) => a.id.localeCompare(b.id));
    lines.push(`## 클러스터: ${label} (${members.length}개)\n\n`);
    lines.push("| ID | Claim | Tags | Links |\n");
    lines.push("|----|-------|------|-------|\n");
    for (const m of members) {
      const tagStr = escapeCell(m.tags.join(", "));
      const linkStr = escapeCell(m.outIds.join(", "));
      lines.push(`| ${m.id} | ${m.claim} | ${tagStr} | ${linkStr} |\n`);
    }
    lines.push("\n");
  }

  const vaultIndexPath = normalizePath(VAULT_INDEX_PATH);
  await writeFile(app, vaultIndexPath, lines.join(""));

  // ── GRAPH.md ──────────────────────────────────────────
  const graphLines: string[] = [];
  graphLines.push("# GRAPH\n\n");
  graphLines.push("> Directed adjacency list. Auto-generated by Cortex Phase 2.\n\n");
  // Sort by id for stable diff
  const sortedNodes: string[] = [];
  store.forEachNode((id, attrs) => {
    if (attrs.isPhantom) return;
    sortedNodes.push(id);
  });
  sortedNodes.sort((a, b) => a.localeCompare(b));

  for (const id of sortedNodes) {
    const out = outNeighbors(store, id);
    if (out.length === 0) continue;
    graphLines.push(`${id} → ${out.join(", ")}\n`);
  }

  const graphPath = normalizePath(GRAPH_PATH);
  await writeFile(app, graphPath, graphLines.join(""));

  // Stats
  let realCount = 0;
  store.forEachNode((_id, attrs) => {
    if (!attrs.isPhantom) realCount++;
  });

  return {
    vaultIndexPath,
    graphPath,
    clusterCount: orderedClusters.length,
    noteCount: realCount,
    edgeCount: store.size(),
  };
}

// ─── helpers ─────────────────────────────────────────────

function outNeighbors(store: GraphStore, id: string): string[] {
  const seen = new Set<string>();
  const g = store.inner();
  if (!g.hasNode(id)) return [];
  g.forEachOutNeighbor(id, (target) => {
    const t = store.getNode(target);
    // Skip phantoms in the rendered output (cleaner VAULT_INDEX).
    if (t && t.isPhantom) return;
    seen.add(target);
  });
  return [...seen].sort();
}

/** Escape pipe and newline characters in markdown table cells. */
function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

async function writeFile(app: App, path: string, content: string): Promise<void> {
  const existing = app.vault.getAbstractFileByPath(path);
  if (existing) {
    await app.vault.adapter.write(path, content);
  } else {
    await app.vault.create(path, content);
  }
}
