/**
 * Default templates for `cortex.schema.md` and `_index/IDENTITY.md`.
 *
 * These are populated on `Cortex: 스키마 초기화`. The user is expected to
 * edit them to reflect their actual vault philosophy. The plugin reads
 * them back at runtime to drive lint and (in later phases) drift detection.
 *
 * Design intent (from Phase 1 plan §7):
 *   - Schema = filter funnel: every input must pass through the same lens.
 *   - IDENTITY.md = vault's "voice": god nodes + cluster gravity, manually
 *     curated to survive silent mutation by automated processes.
 */

const ISO_TODAY = (): string => new Date().toISOString().slice(0, 10);

export const SCHEMA_FILE_PATH = "cortex.schema.md";
export const IDENTITY_FILE_PATH = "_index/IDENTITY.md";
export const LINT_REPORT_PATH = "_index/CORTEX_LINT_REPORT.md";

/**
 * Default contents for `cortex.schema.md`.
 * YAML frontmatter encodes the operational contract; the body is human-
 * readable narrative the user can rewrite freely.
 */
export function defaultSchemaTemplate(): string {
  return `---
version: 1
vault_purpose: |
  여기에 vault의 목적을 기술하세요. 두세 문장이면 충분합니다.
  예) "지식을 외화하여 사고의 도구로 삼는 second brain. 5개 도구의 정수를 통합한다."
core_clusters: []
allowed_tags: []
required_frontmatter:
  permanent:
    - id
    - claim
    - cluster
    - tags
  raw:
    - tags
folder_rules:
  - path: "0 raw/"
    type: raw
  - path: "1 wiki/concepts/"
    type: compiled
  - path: "1 wiki/entities/"
    type: compiled
  - path: "1 wiki/candidates/"
    type: candidates
  - path: "1 wiki/outputs/"
    type: outputs
  - path: "2 Permanent/"
    type: permanent
  - path: "3 Archive/"
    type: archive
forbidden_words: []
---

# Cortex Schema — 운영 계약

이 문서는 **Cortex 플러그인이 vault를 검증할 때 사용하는 계약**입니다.
지난 대화에서 확정한 정체성 보존 5앵커 중 첫 번째 — \"필터-깔때기\" 역할.

## 1. vault_purpose

vault가 무엇을 위한 공간인지를 한 문단으로 정의합니다. 새 노트가 들어올 때
이 문장이 \"이 노트가 여기에 속하는가?\"의 첫 기준이 됩니다.

## 2. core_clusters

vault가 자연스럽게 형성한 주요 클러스터 이름. Phase 2에서 Louvain 결과를
참고해 채워집니다. 수동으로 잠그고 싶은 클러스터를 여기에 넣어두면
drift 감지의 기준선이 됩니다.

## 3. allowed_tags

태그 화이트리스트. 비어 있으면(\\\`[]\\\`) 제한 없음.
화이트리스트 모드를 켜고 싶으면 사용할 태그 목록을 명시하세요.

## 4. required_frontmatter

**permanent** 폴더(2 Permanent/) 노트는 \\\`id\\\`, \\\`claim\\\`, \\\`cluster\\\`, \\\`tags\\\`가
반드시 있어야 합니다. **raw** 폴더(0 raw/) 노트는 \\\`tags\\\`만 있어도 됩니다.
필요에 따라 항목을 추가/삭제하세요.

## 5. folder_rules

폴더 경로 → 노트 유형 매핑. lint가 \"raw 폴더에 id가 있는 영구노트가
들어 있다\" 같은 위반을 잡는 기준입니다.

| type | 의미 |
|---|---|
| \\\`raw\\\` | 신규/불변 입력 (id 없음) |
| \\\`compiled\\\` | wiki/concepts, wiki/entities (자동 생성, provenance 라벨) |
| \\\`candidates\\\` | 승인 대기 (사람이 검토 후 promote) |
| \\\`outputs\\\` | save-first 쿼리 결과 |
| \\\`permanent\\\` | 영구노트 (Folgezettel id, 사람의 손이 들어간 글) |
| \\\`archive\\\` | 처리 완료 raw |

## 6. forbidden_words

vault의 \"맛(taste)\"에 어긋나는 단어 목록. 비어 있으면 검사 안 함.
형님이 의도적으로 피하는 표현(예: 클리셰, 과장된 마케팅 용어)을 적어두면
lint가 새 노트에서 등장 시 경고합니다.

---

## 변경 이력

| 날짜 | 항목 | 사유 |
|---|---|---|
| ${ISO_TODAY()} | 초기 생성 | Cortex Phase 1 — 자동 생성 |
`;
}

/**
 * Default contents for `_index/IDENTITY.md`.
 * Captures the vault's "voice" via god nodes and cluster gravity.
 * Phase 2 fills the auto sections; the user owns the manual sections.
 */
export function defaultIdentityTemplate(): string {
  return `---
version: 1
last_reviewed: "${ISO_TODAY()}"
manual_god_nodes: []
auto_god_nodes: []
core_clusters: []
---

# Vault Identity — 정체성 코어

지난 대화에서 합의한 5앵커 중 ③ \"god nodes\" + ② \"누적된 클러스터\"의 명문화.
**Cortex Phase 2가 PageRank/Louvain 결과로 자동 채우는 섹션과 형님이 직접
잠그는 섹션이 분리됩니다.**

## God Nodes

vault에서 중력이 가장 강한 노드들 — 새 노트를 빨아들이는 코어. 흔들리면
정체성이 흔들리는 신호.

### 🔒 Manual (locked)

형님이 직접 잠근 god nodes. **자동 추출이 이 목록을 덮어쓰지 않습니다.**
새 노트를 받아들이는 기준이 무엇인지 명시적으로 적어두세요.

> _Phase 2 자동 추출 결과를 본 뒤 5개 정도 골라 여기에 잠그는 것을 권장._

(아직 비어있음. Phase 2 끝나면 \`auto_god_nodes\`를 보고 결정.)

### 🤖 Auto (latest scan)

Cortex가 PageRank로 자동 추출한 god nodes. **재계산할 때마다 갱신됩니다.**

> _Phase 2 구현 후 자동 채워짐._

## Core Clusters (Louvain)

vault가 자연스럽게 형성한 클러스터 — 중력장.

> _Phase 2 구현 후 자동 채워짐._

## Drift History

분기별 god nodes/cluster 비교 결과. 흔들림이 누적되는지 추적.

> _Phase 5 (Lint + Drift) 구현 후 자동 채워짐._

---

## 운영 원칙

1. **자동은 제안일 뿐, 잠금은 형님 권한**: \\\`auto_god_nodes\\\`가 \\\`manual_god_nodes\\\`를
   덮어쓰지 않습니다. 형님이 받아들일 때만 옮겨 쓰세요.
2. **분기 1회 리뷰**: \\\`last_reviewed\\\` 갱신과 함께 god nodes를 다시 검토.
3. **drift는 알람일 뿐**: 코어 흔들림이 감지돼도 자동 \"수정\"은 하지 않습니다.
   판단은 사람이.
`;
}

/**
 * Header for the lint report file. The plugin overwrites the file on each
 * run, so this template is rendered fresh every time.
 */
export function lintReportHeader(scannedAt: number, filesScanned: number, violations: number): string {
  const ts = new Date(scannedAt).toISOString().replace("T", " ").slice(0, 19);
  return `# Cortex Lint Report

> Generated by Cortex v0.0.1 on ${ts}
> Files scanned: **${filesScanned}** · Violations: **${violations}**

`;
}
